services:
  develop:
    container_name: smash64-dev-smash64-online-develop
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
        ALPINE_VERSION: ${ALPINE_VERSION:-3.18}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
    volumes:
      - ./:/src
